### ISSUE TITLE
定义模型

### ISSUE THREAD

**Issue by wzq12322** [zgcr/SimpleAICV_pytorch_training_examples#30]
作者您好，请问一下您的代码当中是否可以自定义模型呢，我想自己定义一个resnet110网络是否可以通过将参数修改成[3,4,26,3]来实现呢

**Comment by zgcr** [comment]
> 作者您好，请问一下您的代码当中是否可以自定义模型呢，我想自己定义一个resnet110网络是否可以通过将参数修改成[3,4,26,3]来实现呢

你好，这个库的使用非常灵活，你可以任意自定义数据读取类、数据增强类、模型定义类、损失函数类，甚至train和test的pipeline本身也可以自行定义。在simpleAICV目录下调用的各种定义类可以视为是公用的类，如果同时有多个实验在运行的话，不建议直接修改simpleAICV目录下的各个类定义，否则可能会导致其他正在训练的实验报错退出。

        一般来说，如果是需要临时性地添加或者修改某些类，可以这么修改。以你要自己定义一个resnet110网络为例，我假设你现在要做的是在ImageNet1k数据集上做分类任务，那么你可以在classification_training/imagenet/目录下copy原有的resnet50实验配置文件夹，重命名为resnet110文件夹，重命名后的文件夹下的checkpoint文件夹和log文件夹直接删掉。然后，这个文件夹下面还有train_config.py和test_config.py两个配置文件，和对应的脚本train.sh和test.sh。你要做的是在这个文件夹下临时创建一个resnet110.py文件，在这个文件夹中把你的resnet110网络定义类写进去，然后，在train_config.py和test_config.py文件中把这个resnet110网络定义类import进去，替换原有的resnet50网络。这样，你就可以开始训练了。如果后续你认为这个resnet110网络类需要长期保留，可以把它写到simpleAICV/classification/backbones/resnet.py文件中即可。同样地，如果要修改数据读取类、数据增强类、模型定义类、损失函数类，也都是按照这种思路修改即可。如果您还想修改train和test的pipeline，可以把tools目录下的train_classification_model.py和 test_classification_model.py复制一份到实验配置文件夹下，然后在复制的文件中修改。最后，只需要修改train.sh和test.sh调用的train_classification_model.py和 test_classification_model.py路径即可。

**Comment by wzq12322** [comment]
> > 作者您好，请问一下您的代码当中是否可以自定义模型呢，我想自己定义一个resnet110网络是否可以通过将参数修改成[3,4,26,3]来实现呢
> 
> 你好，这个库的使用非常灵活，你可以任意自定义数据读取类、数据增强类、模型定义类、损失函数类，甚至train和test的pipeline本身也可以自行定义。在simpleAICV目录下调用的各种定义类可以视为是公用的类，如果同时有多个实验在运行的话，不建议直接修改simpleAICV目录下的各个类定义，否则可能会导致其他正在训练的实验报错退出。
> 
> 一般来说，如果是需要临时性地添加或者修改某些类，可以这么修改。以你要自己定义一个resnet110网络为例，我假设你现在要做的是在ImageNet1k数据集上做分类任务，那么你可以在classification_training/imagenet/目录下copy原有的resnet50实验配置文件夹，重命名为resnet110文件夹，重命名后的文件夹下的checkpoint文件夹和log文件夹直接删掉。然后，这个文件夹下面还有train_config.py和test_config.py两个配置文件，和对应的脚本train.sh和test.sh。你要做的是在这个文件夹下临时创建一个resnet110.py文件，在这个文件夹中把你的resnet110网络定义类写进去，然后，在train_config.py和test_config.py文件中把这个resnet110网络定义类import进去，替换原有的resnet50网络。这样，你就可以开始训练了。如果后续你认为这个resnet110网络类需要长期保留，可以把它写到simpleAICV/classification/backbones/resnet.py文件中即可。同样地，如果要修改数据读取类、数据增强类、模型定义类、损失函数类，也都是按照这种思路修改即可。如果您还想修改train和test的pipeline，可以把tools目录下的train_classification_model.py和 test_classification_model.py复制一份到实验配置文件夹下，然后在复制的文件中修改。最后，只需要修改train.sh和test.sh调用的train_classification_model.py和 test_classification_model.py路径即可。

感谢您的回复！通过您的指导我已经开始训练自己的resnet模型了，感谢！

**Comment by wzq12322** [comment]
作者您好，我使用了自己训练的resnet110模型，精准度是这个
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/a1c0e7c9-1ac7-4f01-9ee4-424667725d59)
但是当我将这个resnet110模型作为教师模型，resnet50作为学生模型在cifar-100上训练时，出现了这样的问题
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/23dd7e96-5b9e-45fa-bbba-c7f74735996a)
而且训练的时候教师模型的精准率下降的厉害
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/ff334e90-dd75-4c9d-9bf1-86be9d568d65)
但是使用您提供的预训练模型101作为教师模型，resnet50作为学生模型就不会出现这样的问题
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/898afb5a-ffb0-4eb9-91bc-04e6b214a3bc)
can'shu'ke'yi'zheng参数可以正常加载，而且训练的精度也不错
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/06910260-54a6-4a0e-85af-817ee5fc47ea)
nin'd
这是我自己定义的resnet110
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/1a36173d-442b-4aaf-aab5-bf2a4cc1ca18)
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/c5311785-b731-49a8-a603-f16cc2d40f4d)
请问一下作者这个参数加载的问题是我定义模型出错了嘛

**Comment by zgcr** [comment]
> 但是当我将这个resnet110模型作为教师模型，resnet50作为学生模型在cifar-100上训练时，出现了这样的问题

在cifar100上训练时，resnet50的前两层相比于在Imagenet数据集上训练的resnet50前两层有变化，应该是因为这个导致参数没加载进去。
如果要在cifar100上训练resnet50，可以使用simpleAICV/classification/backbones/resnetforcifar.py定义的resnet50，如果是在其他数据集上训练resnet50，使用simpleAICV/classification/backbones/resnet.py中定义的resnet50。
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/19390485/99afcfbc-558b-4459-8ba6-6a9b37e8eefc)
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/19390485/b3618879-f624-4a8f-8d63-6ef583ed9fd5)

**Comment by wzq12322** [comment]
> > 但是当我将这个resnet110模型作为教师模型，resnet50作为学生模型在cifar-100上训练时，出现了这样的问题
> 
> 在cifar100上训练时，resnet50的前两层相比于在Imagenet数据集上训练的resnet50前两层有变化，应该是因为这个导致参数没加载进去。 如果要在cifar100上训练resnet50，可以使用simpleAICV/classification/backbones/resnetforcifar.py定义的resnet50，如果是在其他数据集上训练resnet50，使用simpleAICV/classification/backbones/resnet.py中定义的resnet50。 ![image](https://user-images.githubusercontent.com/19390485/248734088-99afcfbc-558b-4459-8ba6-6a9b37e8eefc.png) ![image](https://user-images.githubusercontent.com/19390485/248734170-b3618879-f624-4a8f-8d63-6ef583ed9fd5.png)

不好意思，发错截图了....
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/475c4e54-529a-4ca8-b64e-b7ff87e65ccb)
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/11f00655-c13c-47f1-b1a2-a91f88fe6262)
这个是我昨天定义的resnet110，我加载的resnet110模型也是从这个resnetcifar目录里加载的
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/1323f510-2eb2-4589-9182-c34584289e1f)

**Comment by wzq12322** [comment]
作者您好，我下载imagenet数据集速度很慢，我想先在cifar上训练您定义的resnet，然后再将训练完成的resnet进行蒸馏学习，我发现您的蒸馏学习的train_distill_classification_model.py文件只能使用在imagenet数据集上训练的resnet网络，当使用在cifar上训练的网络就会出现参数不匹配的错误
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/3acfb666-92ff-4ec4-aa3c-3aca15ff947f)
我在代码里面没有发现要如何修改才可以让参数匹配，请问一下作者可以解答一下嘛

**Comment by zgcr** [comment]
> 作者您好，我下载imagenet数据集速度很慢，我想先在cifar上训练您定义的resnet，然后再将训练完成的resnet进行蒸馏学习，我发现您的蒸馏学习的train_distill_classification_model.py文件只能使用在imagenet数据集上训练的resnet网络，当使用在cifar上训练的网络就会出现参数不匹配的错误 ![image](https://user-images.githubusercontent.com/102721490/248865339-3acfb666-92ff-4ec4-aa3c-3aca15ff947f.png) 我在代码里面没有发现要如何修改才可以让参数匹配，请问一下作者可以解答一下嘛

可以参照simpleAICV/distillation/distillmodel.py 中的KDmodel类自己写一个蒸馏resnetforcifar的KDmodel类。

**Comment by wzq12322** [comment]
> > 作者您好，我下载imagenet数据集速度很慢，我想先在cifar上训练您定义的resnet，然后再将训练完成的resnet进行蒸馏学习，我发现您的蒸馏学习的train_distill_classification_model.py文件只能使用在imagenet数据集上训练的resnet网络，当使用在cifar上训练的网络就会出现参数不匹配的错误 ![image](https://user-images.githubusercontent.com/102721490/248865339-3acfb666-92ff-4ec4-aa3c-3aca15ff947f.png) 我在代码里面没有发现要如何修改才可以让参数匹配，请问一下作者可以解答一下嘛
> 
> 可以参照simpleAICV/distillation/distillmodel.py 中的KDmodel类自己写一个蒸馏resnetforcifar的KDmodel类。

作者您好，我重写了一个cifarkdmodel
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/93deea6b-aa99-464d-8d06-8b31e9d4c505)
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/5537eb11-b724-4127-9935-76eb590fefa2)

修改了teacher和student的tpye还有image_h和image_w
但是运行代码CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.run --nproc_per_node=2 --master_addr 127.0.1.0 --master_port 10000 ../../../tools/train_distill_classification_model.py --work-dir ./
之后还是出现
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/ffd3de1e-4d43-4675-bff8-ed51cc105e5c)
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/38832964-2a49-4c5b-836c-0e0422e40dae)
请问一下这是什么原因呢

**Comment by zgcr** [comment]
> > > 作者您好，我下载imagenet数据集速度很慢，我想先在cifar上训练您定义的resnet，然后再将训练完成的resnet进行蒸馏学习，我发现您的蒸馏学习的train_distill_classification_model.py文件只能使用在imagenet数据集上训练的resnet网络，当使用在cifar上训练的网络就会出现参数不匹配的错误 ![image](https://user-images.githubusercontent.com/102721490/248865339-3acfb666-92ff-4ec4-aa3c-3aca15ff947f.png) 我在代码里面没有发现要如何修改才可以让参数匹配，请问一下作者可以解答一下嘛
> > 
> > 
> > 可以参照simpleAICV/distillation/distillmodel.py 中的KDmodel类自己写一个蒸馏resnetforcifar的KDmodel类。
> 
> 作者您好，我重写了一个cifarkdmodel ![image](https://user-images.githubusercontent.com/102721490/249095543-93deea6b-aa99-464d-8d06-8b31e9d4c505.png) ![image](https://user-images.githubusercontent.com/102721490/249095608-5537eb11-b724-4127-9935-76eb590fefa2.png)
> 
> 修改了teacher和student的tpye还有image_h和image_w 但是运行代码CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.run --nproc_per_node=2 --master_addr 127.0.1.0 --master_port 10000 ../../../tools/train_distill_classification_model.py --work-dir ./ 之后还是出现 ![image](https://user-images.githubusercontent.com/102721490/249095950-ffd3de1e-4d43-4675-bff8-ed51cc105e5c.png) ![image](https://user-images.githubusercontent.com/102721490/249096010-38832964-2a49-4c5b-836c-0e0422e40dae.png) 请问一下这是什么原因呢

看起来是最后两个weight没加载进去，应该是fc层的weight和bias。如果是在cifar100数据集上训练的话，检查一下定义的模型类和加载的预训练权重fc层的num_classes是否都为100。

**Comment by wzq12322** [comment]
> > > > 作者您好，我下载imagenet数据集速度很慢，我想先在cifar上训练您定义的resnet，然后再将训练完成的resnet进行蒸馏学习，我发现您的蒸馏学习的train_distill_classification_model.py文件只能使用在imagenet数据集上训练的resnet网络，当使用在cifar上训练的网络就会出现参数不匹配的错误 ![image](https://user-images.githubusercontent.com/102721490/248865339-3acfb666-92ff-4ec4-aa3c-3aca15ff947f.png) 我在代码里面没有发现要如何修改才可以让参数匹配，请问一下作者可以解答一下嘛
> > > 
> > > 
> > > 可以参照simpleAICV/distillation/distillmodel.py 中的KDmodel类自己写一个蒸馏resnetforcifar的KDmodel类。
> > 
> > 
> > 作者您好，我重写了一个cifarkdmodel ![image](https://user-images.githubusercontent.com/102721490/249095543-93deea6b-aa99-464d-8d06-8b31e9d4c505.png) ![image](https://user-images.githubusercontent.com/102721490/249095608-5537eb11-b724-4127-9935-76eb590fefa2.png)
> > 修改了teacher和student的tpye还有image_h和image_w 但是运行代码CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.run --nproc_per_node=2 --master_addr 127.0.1.0 --master_port 10000 ../../../tools/train_distill_classification_model.py --work-dir ./ 之后还是出现 ![image](https://user-images.githubusercontent.com/102721490/249095950-ffd3de1e-4d43-4675-bff8-ed51cc105e5c.png) ![image](https://user-images.githubusercontent.com/102721490/249096010-38832964-2a49-4c5b-836c-0e0422e40dae.png) 请问一下这是什么原因呢
> 
> 看起来是最后两个weight没加载进去，应该是fc层的weight和bias。如果是在cifar100数据集上训练的话，检查一下定义的模型类和加载的预训练权重fc层的num_classes是否都为100。

感谢您的回复，我马上修改num_classes为100重新训练模型。

**Comment by wzq12322** [comment]
感谢您的回复！我已经开始进行模型学习了
![image](https://github.com/zgcr/SimpleAICV_pytorch_training_examples/assets/102721490/129e94bb-c3b5-4232-99bd-ab6f391f3669)
