### ISSUE TITLE
window下clone不了

### ISSUE THREAD

**Issue by json007** [zgcr/SimpleAICV_pytorch_training_examples#31]
想拜读一下代码，但是clone时出错

(base) PS D:\code> git clone https://github.com/zgcr/SimpleAICV_pytorch_training_examples.git
Cloning into 'SimpleAICV_pytorch_training_examples'...
remote: Enumerating objects: 2761, done.
remote: Counting objects: 100% (2181/2181), done.
remote: Compressing objects: 100% (970/970), done.
remote: Total 2761 (delta 1257), reused 2010 (delta 1129), pack-reused 580
Receiving objects: 100% (2761/2761), 35.31 MiB | 2.01 MiB/s, done.
Resolving deltas: 100% (1588/1588), done.
fatal: cannot create directory at 'simpleAICV/detection/compile_multiscale_deformable_attention/build/temp.linux-x86_64-3.8/root/code/SimpleAICV_pytorch_training_examples_on_ImageNet_COCO_ADE20K/z_dino_main/dino_multiscale_deformable_attention_compile': **Filename too long**
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

(base) PS D:\code>

**Comment by zgcr** [comment]
> 想拜读一下代码，但是clone时出错
> 
> (base) PS D:\code> git clone https://github.com/zgcr/SimpleAICV_pytorch_training_examples.git Cloning into 'SimpleAICV_pytorch_training_examples'... remote: Enumerating objects: 2761, done. remote: Counting objects: 100% (2181/2181), done. remote: Compressing objects: 100% (970/970), done. remote: Total 2761 (delta 1257), reused 2010 (delta 1129), pack-reused 580 Receiving objects: 100% (2761/2761), 35.31 MiB | 2.01 MiB/s, done. Resolving deltas: 100% (1588/1588), done. fatal: cannot create directory at 'simpleAICV/detection/compile_multiscale_deformable_attention/build/temp.linux-x86_64-3.8/root/code/SimpleAICV_pytorch_training_examples_on_ImageNet_COCO_ADE20K/z_dino_main/dino_multiscale_deformable_attention_compile': **Filename too long** warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry with 'git restore --source=HEAD :/'
> 
> (base) PS D:\code>

你好，也可以从网页上Download ZIP下载整套代码。
