### ISSUE TITLE
about celeba-hq datasets

### ISSUE THREAD

**Issue by Pang-0093** [zgcr/SimpleAICV_pytorch_training_examples#32]
Hi, it is an amazing job! Could you please introduce how to build the celeba-hq dataset?

**Comment by zgcr** [comment]
> Hi, it is an amazing job! Could you please introduce how to build the celeba-hq dataset?

https://github.com/CompVis/taming-transformers#celeba-hq    you can find the build steps here.

**Comment by zgcr** [comment]
> 您好！我按照您提供的链接https://github.com/tkarras/progressive_growing_of_gans 去制作celebahq数据集。我遇到两个问题，一个是这个链接代码提到要制作celebahq必须要用pillow==3.1.1而这个版本的pillow只能在python=3.5及更老的python版本中，而这些python版本应该早都被弃用了，这个问题咋解决；还有一个问题是，似乎这个链接代码输出格式为.tfrecords格式（一个我从来没见过的格式），怎么才能得到您这个项目里要求的那样 \train\male \train\female....之类的呢

可以再参考一些网上的教程试试吧，我这个是几个月前做的，并没有留下来当时处理的原始脚本
