### ISSUE TITLE
How to train the Imagnet (which has 300million images) in local machine?

### ISSUE THREAD

**Issue by Valentine520** [zgcr/SimpleAICV_pytorch_training_examples#33]
I just wonder to know what is your computer hardware device, I chose the i5-12400f and RTX4080 to train the just simple Conv model, just have 5 layers, but the speed is so slow, and the training time will cost many years about 100 epochs. And I try to ues AutoDL to train this model , the cpu is 100% utilize but the gpu is just 40%, and the training speed is also very slow.

**Comment by zgcr** [comment]
> I just wonder to know what is your computer hardware device, I chose the i5-12400f and RTX4080 to train the just simple Conv model, just have 5 layers, but the speed is so slow, and the training time will cost many years about 100 epochs. And I try to ues AutoDL to train this model , the cpu is 100% utilize but the gpu is just 40%, and the training speed is also very slow.

你好！这个库里所有的实验都是在AUTODL平台上完成的。绝大多数实验的硬件配置为2卡RTX A5000(24GB显存)，30 核CPU AMD EPYC 7543 32-Core Processor，60GB内存，一些比较大的网络训练时会采用2卡/4卡RTX 4090(24GB显存) ，32 核/64核CPU AMD EPYC 9654 96-Core Processor，120GB/240GB内存的配置。如果你想知道具体的某个实验到底用了哪种显卡，可以在https://huggingface.co/zgcr654321/classification_training/tree/main/imagenet中查到。比如假设我们要看resnet50这个实验，可以在https://huggingface.co/zgcr654321/classification_training/raw/main/imagenet/resnet50/log/train.info.log.2023-03-14中找到这两行记录：

**Comment by Valentine520** [comment]
I have a new question, what is your training and testing time? I try to use
auto-dl, just single 4090 GPU, use vgg-net, the simple version, the paper E
experiment version, that have first 2 and second 3 and following the 5
layer three times, it means i have 5 vgg blocks, and every block have many
layers, this network is a little complicated, I can just get the very
slowly training speed, about 300 batches per second, batches is just the
single image processing, not the batchsize number, maybe there I make the
batches is not very precise, anyway, the training speed is very slow, i
will cost 2 weeks or more time to train this model, and i also don't know
how bad about my neural network structure, if I want to change the model, I
will cost more one week again, it's very hardly to train these big model,
what the special method your team adopt? And what is your training time
about the 3 millions images dataset and the vgg_net, using the whole
ImageNet.

**Comment by Valentine520** [comment]
I'm very apologize about the question about your training time, I check out
your training log, it's really need too much time to train a huge model
with huge dataset, thank you for your answer, wish you have a nice day!
